"""initial M1 and M2 schema

Revision ID: 3dd6709720e9
Revises:
Create Date: 2026-08-29 07:59:24.755170
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3dd6709720e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('customer_code', sa.String(length=80), nullable=True),
    sa.Column('plc_brand', sa.String(length=80), nullable=False),
    sa.Column('plc_series', sa.String(length=80), nullable=False),
    sa.Column('plc_model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('current_import_id', sa.String(length=36), nullable=True),
    sa.Column('current_spec_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('source_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_artifacts_sha256'), 'source_artifacts', ['sha256'], unique=True)
    op.create_table('template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('schema_version', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_table('import_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('current_revision_id', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_project_import_version')
    )
    op.create_index(op.f('ix_import_versions_project_id'), 'import_versions', ['project_id'], unique=False)
    op.create_table('program_workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_path', sa.String(length=512), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_workspaces_project_id'), 'program_workspaces', ['project_id'], unique=True)
    op.create_table('machine_spec_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=24), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['import_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'sequence', name='uq_import_spec_sequence')
    )
    op.create_index(op.f('ix_machine_spec_revisions_content_hash'), 'machine_spec_revisions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_machine_spec_revisions_import_id'), 'machine_spec_revisions', ['import_id'], unique=False)
    op.create_index(op.f('ix_machine_spec_revisions_project_id'), 'machine_spec_revisions', ['project_id'], unique=False)
    op.create_table('program_branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('git_ref', sa.String(length=180), nullable=False),
    sa.Column('base_commit', sa.String(length=64), nullable=True),
    sa.Column('head_commit', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['program_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_workspace_branch_name')
    )
    op.create_index(op.f('ix_program_branches_workspace_id'), 'program_branches', ['workspace_id'], unique=False)
    op.create_table('control_ir_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('spec_revision_id', sa.String(length=36), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_revision_id'], ['machine_spec_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_ir_revisions_content_hash'), 'control_ir_revisions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_control_ir_revisions_project_id'), 'control_ir_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_control_ir_revisions_spec_revision_id'), 'control_ir_revisions', ['spec_revision_id'], unique=False)
    op.create_table('locked_machine_specs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('spec_revision_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_artifact_id'], ['source_artifacts.id'], ),
    sa.ForeignKeyConstraint(['spec_revision_id'], ['machine_spec_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_revision_id')
    )
    op.create_index(op.f('ix_locked_machine_specs_content_hash'), 'locked_machine_specs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_locked_machine_specs_project_id'), 'locked_machine_specs', ['project_id'], unique=False)
    op.create_table('review_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spec_revision_id', sa.String(length=36), nullable=False),
    sa.Column('view', sa.String(length=64), nullable=False),
    sa.Column('confirmed_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spec_revision_id'], ['machine_spec_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_revision_id', 'view', name='uq_spec_confirmation_view')
    )
    op.create_index(op.f('ix_review_confirmations_spec_revision_id'), 'review_confirmations', ['spec_revision_id'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spec_revision_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('sheet', sa.String(length=80), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=160), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('accepted_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spec_revision_id'], ['machine_spec_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_issues_code'), 'validation_issues', ['code'], unique=False)
    op.create_index(op.f('ix_validation_issues_severity'), 'validation_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_issues_spec_revision_id'), 'validation_issues', ['spec_revision_id'], unique=False)
    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('spec_revision_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('control_ir_revision_id', sa.String(length=36), nullable=True),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['program_branches.id'], ),
    sa.ForeignKeyConstraint(['control_ir_revision_id'], ['control_ir_revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_revision_id'], ['machine_spec_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_branch_id'), 'generation_runs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_generation_runs_project_id'), 'generation_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_runs_spec_revision_id'), 'generation_runs', ['spec_revision_id'], unique=False)
    op.create_index(op.f('ix_generation_runs_status'), 'generation_runs', ['status'], unique=False)
    op.create_table('program_commits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=240), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('machine_spec_revision_id', sa.String(length=36), nullable=True),
    sa.Column('control_ir_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['program_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_ir_revision_id'], ['control_ir_revisions.id'], ),
    sa.ForeignKeyConstraint(['machine_spec_revision_id'], ['machine_spec_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_commits_branch_id'), 'program_commits', ['branch_id'], unique=False)
    op.create_index(op.f('ix_program_commits_git_sha'), 'program_commits', ['git_sha'], unique=True)
    op.create_table('program_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_run_id', 'path', name='uq_generation_artifact_path')
    )
    op.create_index(op.f('ix_program_artifacts_content_hash'), 'program_artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_program_artifacts_generation_run_id'), 'program_artifacts', ['generation_run_id'], unique=False)
    op.create_table('test_spec_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_spec_revisions_content_hash'), 'test_spec_revisions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_test_spec_revisions_generation_run_id'), 'test_spec_revisions', ['generation_run_id'], unique=True)
    op.create_table('trace_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_run_id', sa.String(length=36), nullable=False),
    sa.Column('output_path', sa.String(length=512), nullable=False),
    sa.Column('output_symbol', sa.String(length=160), nullable=True),
    sa.Column('output_line', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=160), nullable=False),
    sa.Column('source_sheet', sa.String(length=80), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_links_generation_run_id'), 'trace_links', ['generation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_links_generation_run_id'), table_name='trace_links')
    op.drop_table('trace_links')
    op.drop_index(op.f('ix_test_spec_revisions_generation_run_id'), table_name='test_spec_revisions')
    op.drop_index(op.f('ix_test_spec_revisions_content_hash'), table_name='test_spec_revisions')
    op.drop_table('test_spec_revisions')
    op.drop_index(op.f('ix_program_artifacts_generation_run_id'), table_name='program_artifacts')
    op.drop_index(op.f('ix_program_artifacts_content_hash'), table_name='program_artifacts')
    op.drop_table('program_artifacts')
    op.drop_index(op.f('ix_program_commits_git_sha'), table_name='program_commits')
    op.drop_index(op.f('ix_program_commits_branch_id'), table_name='program_commits')
    op.drop_table('program_commits')
    op.drop_index(op.f('ix_generation_runs_status'), table_name='generation_runs')
    op.drop_index(op.f('ix_generation_runs_spec_revision_id'), table_name='generation_runs')
    op.drop_index(op.f('ix_generation_runs_project_id'), table_name='generation_runs')
    op.drop_index(op.f('ix_generation_runs_branch_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index(op.f('ix_validation_issues_spec_revision_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_severity'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_code'), table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index(op.f('ix_review_confirmations_spec_revision_id'), table_name='review_confirmations')
    op.drop_table('review_confirmations')
    op.drop_index(op.f('ix_locked_machine_specs_project_id'), table_name='locked_machine_specs')
    op.drop_index(op.f('ix_locked_machine_specs_content_hash'), table_name='locked_machine_specs')
    op.drop_table('locked_machine_specs')
    op.drop_index(op.f('ix_control_ir_revisions_spec_revision_id'), table_name='control_ir_revisions')
    op.drop_index(op.f('ix_control_ir_revisions_project_id'), table_name='control_ir_revisions')
    op.drop_index(op.f('ix_control_ir_revisions_content_hash'), table_name='control_ir_revisions')
    op.drop_table('control_ir_revisions')
    op.drop_index(op.f('ix_program_branches_workspace_id'), table_name='program_branches')
    op.drop_table('program_branches')
    op.drop_index(op.f('ix_machine_spec_revisions_project_id'), table_name='machine_spec_revisions')
    op.drop_index(op.f('ix_machine_spec_revisions_import_id'), table_name='machine_spec_revisions')
    op.drop_index(op.f('ix_machine_spec_revisions_content_hash'), table_name='machine_spec_revisions')
    op.drop_table('machine_spec_revisions')
    op.drop_index(op.f('ix_program_workspaces_project_id'), table_name='program_workspaces')
    op.drop_table('program_workspaces')
    op.drop_index(op.f('ix_import_versions_project_id'), table_name='import_versions')
    op.drop_table('import_versions')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_source_artifacts_sha256'), table_name='source_artifacts')
    op.drop_table('source_artifacts')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
